### ISSUE TITLE
Help:  Cancelling sending action bar messages 

### ISSUE THREAD

**Issue by Maitlans** [jaqobb/message-editor#4]
I'm not too sure how to go about cancelling messages being sent, there's this plugin that is conflicting with another plugin sending action bar messages and I just want to completely block it out. Thank you.
![waves](https://user-images.githubusercontent.com/51733032/89705805-39d1df80-d92e-11ea-8dc9-c11587b4d2bf.png)

**Comment by jaqobb** [comment]
Hey, when you get the message's JSON (in this case via message analyzing), prepare the pattern and leave `message-after` completely empty.

For example, in the default configuration file you can find an edited join message:
```yml
message-edits:
- ==: MessageEdit
  message-before-pattern: '\{"extra":\[\{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"([a-zA-Z0-9_]{3,16}) joined the game"\}\],"text":""\}'
  message-after: '{"extra":[{"bold":true,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"$1 joined the game"}],"text":""}'
```
but to completely prevent it from being sent, just empty the `message-after` setting like that:
```yml
message-edits:
- ==: MessageEdit
  message-before-pattern: '\{"extra":\[\{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"([a-zA-Z0-9_]{3,16}) joined the game"\}\],"text":""\}'
  message-after: ''
```
